spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: catalog-service
            uri:
              http://localhost:8081
            predicates:
              - Path=/catalog/**
          - id: profile-service
            uri:
              http://localhost:8084
            predicates:
              - Path=/profile/**
          - id: auth-service
            uri:
              http://localhost:8085
            predicates:
              - Path=/auth/**
              - Path=/user/**