spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/media/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
  main:
    web-application-type: reactive

server:
  port: 8080

jwt:
  secret-key: ${JWT_SECRET_KEY}

eureka:
  instance:
    prefer-ip-address: true # Использовать IP вместо hostname
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

security:
  public-paths: /auth,/profile/get-profile-by-id/,/catalog/product/get-product-by-id/,/catalog/product/get-all-products,/catalog/category/get-products-by-category,/catalog/category/get-all-exists-categories,/catalog/product/get-products-for-main-page

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: DEBUG


