create table cart (
                      id int generated by default as identity primary key ,
                      profile_id int not null ,
                      product_id int not null ,
                      quantity int not null
)